### ISSUE TITLE
Add multiple Definitions to the Container at once, after is has been 'built' by the ContainerBuilder

### ISSUE THREAD

**Issue by holtkamp** [mnapoli/PHP-DI#261]
We would like to add a multiple of (Module-specific) InjectionDefinitions, after the DIC has been built by the ContainerBuilder. 

So instead of:

```
$builder = new \DI\ContainerBuilder();
$builder->addDefinitions(APPLICATION_PATH . '/configs/dependencyInjectionContainerConfig.php');
$builder->addDefinitions(APPLICATION_PATH . '/modules/moduleName1/configs/dependencyInjectionContainerConfig.php');
$builder->addDefinitions(APPLICATION_PATH . '/modules/moduleName2/configs/dependencyInjectionContainerConfig.php');
$container = $builder->build();
```
	
we would like to use:

```
$builder = new \DI\ContainerBuilder();
$builder->addDefinitions(APPLICATION_PATH . '/configs/dependencyInjectionContainerConfig.php');
$container = $builder->build();

//Some routing, determine which Module is requested

//When the requested Module is determined, add specific DIC configuration
$container->addDefinitions(APPLICATION_PATH . '/modules/moduleName1/configs/dependencyInjectionContainerConfig.php');
```

This way, only the required configurations are set for a specific Module. However, it seems not possible to add multiple Definitions at once. Adding Definitions one by one seems not possible because ArrayDefinitionSource.definitions is not publicly accessible...

Is the aforementioned appraoch bad-practice? Or...

**Comment by mnapoli** [comment]
Yes I would say it's generally bad practice for the following reasons:

- cache: if you use a cache, the container should always have the same definitions, else there's a risk that definition `A` is cached and then it's overwritten/changed at runtime, and the cache still holds the old definition
- already injected instances: if you inject `A` into `B`, then you change what `A` should be, PHP-DI can't un-inject `A` and re-inject the new value

For those reasons, PHP-DI is optimized to work with a "static" configuration/application wiring. I.e. you configure your application once, then build it (-> the "container builder" step) and then the wiring of objects is supposed to be frozen (to avoid the weird cases I mentioned).

But the use case you have is not uncommon. I have discussed this already with [Mike van Riel](https://twitter.com/mvriel) who had the same question for rewriting phpDocumentor with plugins, and we also faced the same issue with plugins for [Piwik](https://github.com/piwik/piwik). In the end we moved to a 2 step scenario:

1. prepare the application (i.e. configure the container with all the config files)
2. run the application (the container is use for read only)

It takes some effort to do this, but it's definitely better. And this is also how Symfony works for example.

Now I don't know all the details of your application, and maybe in your case being able to load and change the definitions at runtime is actually better. But the current status is: it's not really meant for that. However we could discuss ideas to change that if you are sure that's what you need. Just be aware of the problems associated to this.

(I hope my comment made sense, it's late here and I'm really tired ;) )

**Comment by holtkamp** [comment]
Thanks for the detailed response, I understand your stance. 

The scenario is
- old Zend Framework 1 application, in need for an upgrade, since end-of-life of the framework is imminent
- step by step we phase out Zend Framework 1 specific functionality
- Zend Framework 1 allows the use of [ViewHelpers](http://framework.zend.com/manual/1.12/en/zend.view.helpers.html) in templates (also known as [ViewScripts](http://framework.zend.com/manual/1.12/en/zend.view.scripts.html))
- these ViewHelpers and the way they are loaded, are too much 'magic' for me, I want them to be dependencies of a [Zend Framework 2 ViewModel](http://framework.zend.com/manual/current/en/modules/zend.view.quick-start.html#controllers-and-view-models). Eventually we might/should be able to use auto-wiring to instantiate a specific specialised ViewModel with the used ViewHelpers
- as a transition while phasing out ZF1 specifics (the ViewHelper [plugin loader](http://framework.zend.com/manual/1.12/en/zend.loader.pluginloader.html) which loads the ViewHelpers), I wanted to use the DIC
- by letting a ```DIC::__callStatic($resourceName, array $parameters)``` invoke the ```$container->get()``` / ```$container->make()```, we are now able to invoke a ViewHelper like this: ```$button = DIC::getButtonViewHelper()->setLabel('Nice Button');```
- I know that using a static lookup like this is not advised and the (in)direct use of $container->get() should be avoided , but as said, this is temporary use until we can use actual ViewModels instead of ViewScripts
- Some of the ViewHelpers in different Modules have the same name, while having a different implementation / FQCN. This is where the conflict pops up, for example:
 - Module1\View\Helper\Button (listens to DIC::getButtonViewHelper())
 - Module2\View\Helper\Button (also listens to DIC::getButtonViewHelper() => conflict)
 
So suppose we configure ALL dependencies used in the application (which has around 10 Modules) at once / before routing, naming conflicts might occur. In that case we should use the Fully Qualified Namespace of the ViewHelper to fetch it from the DIC, but that might decrease the ease of use, maybe this is a temporary solution: DIC::getButtonViewHelper($moduleName)

Just started to migrate all ViewHelpers of one Module to the DIC, will think of a (temporary) solution for this while doing this. Suggestions / feedback is welcome. Just started working with DIC, seems powerful but still a challenge :smile:. Step by step we will find out!

**Comment by mnapoli** [comment]
I see your problem. Honesty I think the root cause is (as long as we consider `DIC::getButtonViewHelper()` to be somewhat the same as `$container->get(...)`) that you have conflicts for the same entry name.

I understand where you come from, dealing with legacy and big application you sometimes have to make tradeoffs. So I don't think your solution is wrong. But I don't think for this case it's a problem with PHP-DI itself.

As for ideas, maybe you could indeed use the module name in the name but it indeed reduces simplicity. You could also name your helpers slightly differently… After all in the same application you have 2 view helpers for buttons that behave differently, you need a way to distinguish them.

I'm closing the issue but the discussion is still open ;)

**Comment by holtkamp** [comment]
Ok, I agree. 

Summarising: the advised approach would be:
- register all dependencies 
 - possibly gradually using separate configurations, one for each Module / SubSystem
 - using a unique name, typically using the FQCN
- build the container

Before looking up a resource like ```ButtonViewHelper```, we now iterate over a number of namespaces to resolve the actual name of the dependency to lookup. The order of the Modules would suggest which names are preferred:

```
- Module1\View\Helper\Button
- Module2\View\Helper\Button
- ModuleN\View\Helper\Button
```

For now this seems a viable approach :smile:
